### PR TITLE
Bug fix for bypassing ground check

### PR DESCRIPTION
**Pull request by Baldie-dev**
I just did a small change in IL for the transpiler.

### CODE REVIEW

**Comment by Baldie-dev** [comment]
There is small issue, still working on it

**Comment by Baldie-dev** [comment]
Should be working now

**Comment by Baldie-dev** [comment]
I am doing final testing, but this seems to be final version :D

**Comment by Baldie-dev** [comment]
Tested with 3 instances and no issues found [video](https://youtu.be/5a7OpT973tI).

**Review by hubastard — APPROVED** [review]

**Pull request merged**
